AWSTemplateFormatVersion: '2010-09-09'
Description: Static SPA hosting (S3 private + CloudFront OAC) for Vite/Vue

Parameters:
  ProjectName:
    Type: String
    Default: csv-upload-front

  BucketName:
    Type: String
    Default: ""
    Description: Optional. If empty, CloudFormation will generate a bucket name.

  PriceClass:
    Type: String
    Default: PriceClass_200
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All

  CustomDomainName:
    Type: String
    Default: ""
    Description: Optional. e.g. app.example.com (leave empty to skip)

  AcmCertificateArnUsEast1:
    Type: String
    Default: ""
    Description: Optional. ACM cert ARN in us-east-1 for CloudFront (leave empty to skip)

Conditions:
  BucketNameProvided: !Not [!Equals [!Ref BucketName, ""]]
  UseCustomDomain: !And
    - !Not [!Equals [!Ref CustomDomainName, ""]]
    - !Not [!Equals [!Ref AcmCertificateArnUsEast1, ""]]

Resources:
  FrontBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [BucketNameProvided, !Ref BucketName, !Ref "AWS::NoValue"]
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${ProjectName}-security-headers"
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true

  FrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${ProjectName} static SPA"
        DefaultRootObject: index.html
        PriceClass: !Ref PriceClass
        HttpVersion: http2and3

        Origins:
          - Id: s3origin
            DomainName: !GetAtt FrontBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref FrontOAC

        DefaultCacheBehavior:
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

        ViewerCertificate: !If
          - UseCustomDomain
          - AcmCertificateArn: !Ref AcmCertificateArnUsEast1
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

        Aliases: !If
          - UseCustomDomain
          - [!Ref CustomDomainName]
          - !Ref "AWS::NoValue"

  FrontBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontDistribution}"

Outputs:
  BucketName:
    Value: !Ref FrontBucket
    Description: Upload built files (dist/) to this bucket

  CloudFrontDomainName:
    Value: !GetAtt FrontDistribution.DomainName
    Description: Access your app via this CloudFront domain

  CloudFrontDistributionId:
    Value: !Ref FrontDistribution
    Description: Use this for invalidations
